// Command dump-residue runs the enrichment over dataset versions and dumps
// the unique items the deterministic parser could not fully resolve: the
// candidate set for an LLM (or manual) residue pass. Items are deduplicated
// by text and grouped by failure category.
//
//	go run ./cmd/dump-residue [-versions 0] > notes/residue.txt
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/ottrec/data-enrichment/enrich"
	"github.com/ottrec/data-enrichment/internal/dataver"
)

var (
	cachePath = flag.String("cache", "/tmp/ottrec-data.db", "ottrecdata cache path")
	nVersions = flag.Int("versions", 0, "number of most recent versions to process (0 = all)")
)

// categories, in priority order, of ambiguity markers whose items would
// benefit from a second (LLM/manual) parsing pass. Intrinsic ambiguities the
// text genuinely doesn't answer (multiple candidate activities, unconfirmed
// years, inferred meridiems) are excluded: a model can't know those either.
var categories = []string{
	"activity-unmatched",
	"class-unmatched",
	"no-subject",
	"freeform-item",
	"head-unparsed",
	"date-garbled",
	"date-unparsed",
	"date-range-invalid",
	"possible-activity-time",
	"hours-context-unknown",
	"meridiem-ambiguous",
}

type entry struct {
	category   string
	source     string
	dateText   string
	section    string
	rawText    string
	markers    []string
	count      int
	facilities map[string]bool
	group      string // example
}

func main() {
	flag.Parse()
	ctx := context.Background()

	entries := map[string]*entry{}
	add := func(category, source, dateText, section, rawText, facility, group string, markers []string) {
		key := category + "\x00" + dateText + "\x00" + rawText
		e := entries[key]
		if e == nil {
			e = &entry{
				category: category, source: source, dateText: dateText,
				section: section, rawText: rawText, markers: markers,
				facilities: map[string]bool{}, group: group,
			}
			entries[key] = e
		}
		e.count++
		e.facilities[facility] = true
	}

	versions := 0
	var err error
	for ver, data := range dataver.Each(ctx, *cachePath)(&err) {
		if *nVersions > 0 && versions >= *nVersions {
			break
		}
		versions++

		out := enrich.EnrichVersion(ver.ID, data)
		for _, o := range out.Objects {
			switch o.Kind {
			case "unparsed":
				add("unparsed/"+o.Reason, o.Source, o.DateText, o.Section, o.RawText, o.Facility, o.SourceGroup, nil)
			case "notice":
				cat := ""
				for _, c := range categories {
					if slices.Contains(o.Ambiguities, c) {
						cat = c
						break
					}
				}
				if cat == "" {
					continue
				}
				if cat == "date-garbled" && o.Dates != nil {
					continue // repaired: dates resolved despite the garble
				}
				add(cat, o.Source, o.DateText, o.Section, o.RawText, o.Facility, o.SourceGroup, o.Ambiguities)
			}
		}
	}
	if err != nil {
		panic(err)
	}

	// order: unparsed first, then marker categories by the priority list
	catOrder := append([]string{"unparsed/freeform", "unparsed/empty"}, categories...)
	byCat := map[string][]*entry{}
	for _, e := range entries {
		byCat[e.category] = append(byCat[e.category], e)
	}
	for _, es := range byCat {
		slices.SortFunc(es, func(a, b *entry) int {
			if a.count != b.count {
				return b.count - a.count
			}
			return strings.Compare(a.rawText, b.rawText)
		})
	}

	total, instances := 0, 0
	for _, es := range byCat {
		total += len(es)
		for _, e := range es {
			instances += e.count
		}
	}
	fmt.Printf("# Residue: items needing a second parsing pass (LLM or manual)\n")
	fmt.Printf("# generated by cmd/dump-residue over %d versions: %d unique items, %d instances\n", versions, total, instances)

	seen := map[string]bool{}
	for _, cat := range catOrder {
		es := byCat[cat]
		if len(es) == 0 || seen[cat] {
			continue
		}
		seen[cat] = true
		inst := 0
		for _, e := range es {
			inst += e.count
		}
		fmt.Printf("\n## %s (%d unique / %d instances)\n", cat, len(es), inst)
		for _, e := range es {
			fmt.Printf("\n%5dx %s", e.count, e.source)
			if len(e.facilities) == 1 {
				for f := range e.facilities {
					fmt.Printf(" @ %s", f)
				}
			} else {
				fmt.Printf(" @ %d facilities", len(e.facilities))
			}
			if e.group != "" {
				fmt.Printf(" [%s]", e.group)
			}
			fmt.Println()
			if e.section != "" {
				fmt.Printf("       section: %s\n", e.section)
			}
			if e.dateText != "" {
				fmt.Printf("       date:    %s\n", e.dateText)
			}
			fmt.Printf("       text:    %s\n", strings.ReplaceAll(e.rawText, "\n", " / "))
			if rest := otherMarkers(e.markers, e.category); len(rest) > 0 {
				fmt.Printf("       markers: %s\n", strings.Join(rest, ", "))
			}
		}
	}
	// anything in an unexpected category (shouldn't happen)
	for cat := range byCat {
		if !seen[cat] {
			fmt.Fprintf(os.Stderr, "warning: uncategorized %q (%d entries)\n", cat, len(byCat[cat]))
		}
	}
}

func otherMarkers(markers []string, cat string) []string {
	var out []string
	for _, m := range markers {
		if m != cat {
			out = append(out, m)
		}
	}
	return out
}
