// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: enrichment.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Object_Kind int32

const (
	Object_KIND_UNSPECIFIED Object_Kind = 0
	// A parsed notice carrying associations and effects.
	Object_NOTICE Object_Kind = 1
	// Freeform text nothing could be extracted from.
	Object_UNPARSED Object_Kind = 2
	// Structure and boilerplate kept only so the output accounts for
	// every fragment of the source: headings, date-context lines,
	// contact blurbs, collapsed duplicates (see reason).
	Object_IGNORED Object_Kind = 3
)

// Enum value maps for Object_Kind.
var (
	Object_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "NOTICE",
		2: "UNPARSED",
		3: "IGNORED",
	}
	Object_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"NOTICE":           1,
		"UNPARSED":         2,
		"IGNORED":          3,
	}
)

func (x Object_Kind) Enum() *Object_Kind {
	p := new(Object_Kind)
	*p = x
	return p
}

func (x Object_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Object_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_enrichment_proto_enumTypes[0].Descriptor()
}

func (Object_Kind) Type() protoreflect.EnumType {
	return &file_enrichment_proto_enumTypes[0]
}

func (x Object_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// The enrichment output for one dataset version, derived from the freeform
// notification/special-hours/schedule-changes HTML of an ottrec.v1.Data
// snapshot. Every fragment of source text is accounted for by exactly one
// Object in the flat list; the facility hierarchy references objects by id at
// the most specific level the association is guaranteed for.
//
// Date fields are encoded as in ottrec.v1 (YYYYMMDDW ints, see
// ottrec.v1.Schedule._daydates); clock fields are minutes from 00:00 as in
// ottrec.v1.TimeRange.
type Output struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Version    string                 `protobuf:"bytes,1,opt,name=version"`
	xxx_hidden_Generated  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=generated"`
	xxx_hidden_Objects    *[]*Object             `protobuf:"bytes,3,rep,name=objects"`
	xxx_hidden_Facilities *[]*Facility           `protobuf:"bytes,4,rep,name=facilities"`
	xxx_hidden_Stats      map[string]int32       `protobuf:"bytes,5,rep,name=stats" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_enrichment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Output) GetVersion() string {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return ""
}

func (x *Output) GetGenerated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Generated
	}
	return nil
}

func (x *Output) GetObjects() []*Object {
	if x != nil {
		if x.xxx_hidden_Objects != nil {
			return *x.xxx_hidden_Objects
		}
	}
	return nil
}

func (x *Output) GetFacilities() []*Facility {
	if x != nil {
		if x.xxx_hidden_Facilities != nil {
			return *x.xxx_hidden_Facilities
		}
	}
	return nil
}

func (x *Output) GetStats() map[string]int32 {
	if x != nil {
		return x.xxx_hidden_Stats
	}
	return nil
}

func (x *Output) SetVersion(v string) {
	x.xxx_hidden_Version = v
}

func (x *Output) SetGenerated(v *timestamppb.Timestamp) {
	x.xxx_hidden_Generated = v
}

func (x *Output) SetObjects(v []*Object) {
	x.xxx_hidden_Objects = &v
}

func (x *Output) SetFacilities(v []*Facility) {
	x.xxx_hidden_Facilities = &v
}

func (x *Output) SetStats(v map[string]int32) {
	x.xxx_hidden_Stats = v
}

func (x *Output) HasGenerated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Generated != nil
}

func (x *Output) ClearGenerated() {
	x.xxx_hidden_Generated = nil
}

type Output_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Version    string
	Generated  *timestamppb.Timestamp
	Objects    []*Object
	Facilities []*Facility
	Stats      map[string]int32
}

func (b0 Output_builder) Build() *Output {
	m0 := &Output{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Version = b.Version
	x.xxx_hidden_Generated = b.Generated
	x.xxx_hidden_Objects = &b.Objects
	x.xxx_hidden_Facilities = &b.Facilities
	x.xxx_hidden_Stats = b.Stats
	return m0
}

// Facility mirrors an ottrec.v1.Facility (joined by name), holding
// facility-scoped object refs and the schedule groups that have content.
type Facility struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name    string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Objects []string               `protobuf:"bytes,2,rep,name=objects"`
	xxx_hidden_Groups  *[]*Group              `protobuf:"bytes,3,rep,name=groups"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Facility) Reset() {
	*x = Facility{}
	mi := &file_enrichment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facility) ProtoMessage() {}

func (x *Facility) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Facility) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Facility) GetObjects() []string {
	if x != nil {
		return x.xxx_hidden_Objects
	}
	return nil
}

func (x *Facility) GetGroups() []*Group {
	if x != nil {
		if x.xxx_hidden_Groups != nil {
			return *x.xxx_hidden_Groups
		}
	}
	return nil
}

func (x *Facility) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Facility) SetObjects(v []string) {
	x.xxx_hidden_Objects = v
}

func (x *Facility) SetGroups(v []*Group) {
	x.xxx_hidden_Groups = &v
}

type Facility_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name    string
	Objects []string
	Groups  []*Group
}

func (b0 Facility_builder) Build() *Facility {
	m0 := &Facility{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Objects = b.Objects
	x.xxx_hidden_Groups = &b.Groups
	return m0
}

// Group mirrors an ottrec.v1.ScheduleGroup (joined by label).
type Group struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Label      string                 `protobuf:"bytes,1,opt,name=label"`
	xxx_hidden_Objects    []string               `protobuf:"bytes,2,rep,name=objects"`
	xxx_hidden_Activities *[]*Activity           `protobuf:"bytes,3,rep,name=activities"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_enrichment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Group) GetLabel() string {
	if x != nil {
		return x.xxx_hidden_Label
	}
	return ""
}

func (x *Group) GetObjects() []string {
	if x != nil {
		return x.xxx_hidden_Objects
	}
	return nil
}

func (x *Group) GetActivities() []*Activity {
	if x != nil {
		if x.xxx_hidden_Activities != nil {
			return *x.xxx_hidden_Activities
		}
	}
	return nil
}

func (x *Group) SetLabel(v string) {
	x.xxx_hidden_Label = v
}

func (x *Group) SetObjects(v []string) {
	x.xxx_hidden_Objects = v
}

func (x *Group) SetActivities(v []*Activity) {
	x.xxx_hidden_Activities = &v
}

type Group_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Label      string
	Objects    []string
	Activities []*Activity
}

func (b0 Group_builder) Build() *Group {
	m0 := &Group{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Label = b.Label
	x.xxx_hidden_Objects = b.Objects
	x.xxx_hidden_Activities = &b.Activities
	return m0
}

// Activity mirrors an ottrec.v1.Schedule.Activity, joined by its raw
// unnormalized label (the canonical identifier of an activity within its
// group; the normalized _name is lossy). novel marks activities that only
// exist in a change notice ("Women's only swim, added"), not in the
// published schedule; a novel label is the raw subject phrase of that
// notice.
type Activity struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Label    string                 `protobuf:"bytes,1,opt,name=label"`
	xxx_hidden_Novel    bool                   `protobuf:"varint,2,opt,name=novel"`
	xxx_hidden_Objects  []string               `protobuf:"bytes,3,rep,name=objects"`
	xxx_hidden_Sessions *[]*Session            `protobuf:"bytes,4,rep,name=sessions"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_enrichment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Activity) GetLabel() string {
	if x != nil {
		return x.xxx_hidden_Label
	}
	return ""
}

func (x *Activity) GetNovel() bool {
	if x != nil {
		return x.xxx_hidden_Novel
	}
	return false
}

func (x *Activity) GetObjects() []string {
	if x != nil {
		return x.xxx_hidden_Objects
	}
	return nil
}

func (x *Activity) GetSessions() []*Session {
	if x != nil {
		if x.xxx_hidden_Sessions != nil {
			return *x.xxx_hidden_Sessions
		}
	}
	return nil
}

func (x *Activity) SetLabel(v string) {
	x.xxx_hidden_Label = v
}

func (x *Activity) SetNovel(v bool) {
	x.xxx_hidden_Novel = v
}

func (x *Activity) SetObjects(v []string) {
	x.xxx_hidden_Objects = v
}

func (x *Activity) SetSessions(v []*Session) {
	x.xxx_hidden_Sessions = &v
}

type Activity_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Label    string
	Novel    bool
	Objects  []string
	Sessions []*Session
}

func (b0 Activity_builder) Build() *Activity {
	m0 := &Activity{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Label = b.Label
	x.xxx_hidden_Novel = b.Novel
	x.xxx_hidden_Objects = b.Objects
	x.xxx_hidden_Sessions = &b.Sessions
	return m0
}

// Session is one concrete date + clock range. objects reference notices
// about a published schedule time (cancellations, closures, changes); added
// reference notices that add this time (it is not in the published
// schedule).
type Session struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Date    int32                  `protobuf:"varint,1,opt,name=date"`
	xxx_hidden_Start   int32                  `protobuf:"varint,2,opt,name=start"`
	xxx_hidden_End     int32                  `protobuf:"varint,3,opt,name=end"`
	xxx_hidden_Objects []string               `protobuf:"bytes,4,rep,name=objects"`
	xxx_hidden_Added   []string               `protobuf:"bytes,5,rep,name=added"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_enrichment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Session) GetDate() int32 {
	if x != nil {
		return x.xxx_hidden_Date
	}
	return 0
}

func (x *Session) GetStart() int32 {
	if x != nil {
		return x.xxx_hidden_Start
	}
	return 0
}

func (x *Session) GetEnd() int32 {
	if x != nil {
		return x.xxx_hidden_End
	}
	return 0
}

func (x *Session) GetObjects() []string {
	if x != nil {
		return x.xxx_hidden_Objects
	}
	return nil
}

func (x *Session) GetAdded() []string {
	if x != nil {
		return x.xxx_hidden_Added
	}
	return nil
}

func (x *Session) SetDate(v int32) {
	x.xxx_hidden_Date = v
}

func (x *Session) SetStart(v int32) {
	x.xxx_hidden_Start = v
}

func (x *Session) SetEnd(v int32) {
	x.xxx_hidden_End = v
}

func (x *Session) SetObjects(v []string) {
	x.xxx_hidden_Objects = v
}

func (x *Session) SetAdded(v []string) {
	x.xxx_hidden_Added = v
}

type Session_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Date    int32
	Start   int32
	End     int32
	Objects []string
	Added   []string
}

func (b0 Session_builder) Build() *Session {
	m0 := &Session{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Date = b.Date
	x.xxx_hidden_Start = b.Start
	x.xxx_hidden_End = b.End
	x.xxx_hidden_Objects = b.Objects
	x.xxx_hidden_Added = b.Added
	return m0
}

// Object is one extracted fragment of source text.
type Object struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id           string                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Kind         Object_Kind            `protobuf:"varint,2,opt,name=kind,enum=ottrec.enrichment.v1.Object_Kind"`
	xxx_hidden_Reason       string                 `protobuf:"bytes,3,opt,name=reason"`
	xxx_hidden_Facility     string                 `protobuf:"bytes,4,opt,name=facility"`
	xxx_hidden_Source       string                 `protobuf:"bytes,5,opt,name=source"`
	xxx_hidden_SourceGroup  string                 `protobuf:"bytes,6,opt,name=source_group,json=sourceGroup"`
	xxx_hidden_Sources      []string               `protobuf:"bytes,7,rep,name=sources"`
	xxx_hidden_DuplicateOf  []string               `protobuf:"bytes,8,rep,name=duplicate_of,json=duplicateOf"`
	xxx_hidden_BlockHash    string                 `protobuf:"bytes,9,opt,name=block_hash,json=blockHash"`
	xxx_hidden_Seq          int32                  `protobuf:"varint,10,opt,name=seq"`
	xxx_hidden_HtmlStart    int32                  `protobuf:"varint,11,opt,name=html_start,json=htmlStart"`
	xxx_hidden_HtmlEnd      int32                  `protobuf:"varint,12,opt,name=html_end,json=htmlEnd"`
	xxx_hidden_Section      string                 `protobuf:"bytes,13,opt,name=section"`
	xxx_hidden_DateText     string                 `protobuf:"bytes,14,opt,name=date_text,json=dateText"`
	xxx_hidden_RawHtml      string                 `protobuf:"bytes,15,opt,name=raw_html,json=rawHtml"`
	xxx_hidden_RawText      string                 `protobuf:"bytes,16,opt,name=raw_text,json=rawText"`
	xxx_hidden_Dates        *DateSpan              `protobuf:"bytes,17,opt,name=dates"`
	xxx_hidden_Time         *TimeAssoc             `protobuf:"bytes,18,opt,name=time"`
	xxx_hidden_Effects      *[]*Effect             `protobuf:"bytes,19,rep,name=effects"`
	xxx_hidden_MatchQuality string                 `protobuf:"bytes,20,opt,name=match_quality,json=matchQuality"`
	xxx_hidden_Phrase       string                 `protobuf:"bytes,21,opt,name=phrase"`
	xxx_hidden_Amenity      string                 `protobuf:"bytes,22,opt,name=amenity"`
	xxx_hidden_Candidates   []string               `protobuf:"bytes,23,rep,name=candidates"`
	xxx_hidden_Ambiguities  []string               `protobuf:"bytes,24,rep,name=ambiguities"`
	xxx_hidden_ProducedBy   string                 `protobuf:"bytes,25,opt,name=produced_by,json=producedBy"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_enrichment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Object) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Object) GetKind() Object_Kind {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return Object_KIND_UNSPECIFIED
}

func (x *Object) GetReason() string {
	if x != nil {
		return x.xxx_hidden_Reason
	}
	return ""
}

func (x *Object) GetFacility() string {
	if x != nil {
		return x.xxx_hidden_Facility
	}
	return ""
}

func (x *Object) GetSource() string {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return ""
}

func (x *Object) GetSourceGroup() string {
	if x != nil {
		return x.xxx_hidden_SourceGroup
	}
	return ""
}

func (x *Object) GetSources() []string {
	if x != nil {
		return x.xxx_hidden_Sources
	}
	return nil
}

func (x *Object) GetDuplicateOf() []string {
	if x != nil {
		return x.xxx_hidden_DuplicateOf
	}
	return nil
}

func (x *Object) GetBlockHash() string {
	if x != nil {
		return x.xxx_hidden_BlockHash
	}
	return ""
}

func (x *Object) GetSeq() int32 {
	if x != nil {
		return x.xxx_hidden_Seq
	}
	return 0
}

func (x *Object) GetHtmlStart() int32 {
	if x != nil {
		return x.xxx_hidden_HtmlStart
	}
	return 0
}

func (x *Object) GetHtmlEnd() int32 {
	if x != nil {
		return x.xxx_hidden_HtmlEnd
	}
	return 0
}

func (x *Object) GetSection() string {
	if x != nil {
		return x.xxx_hidden_Section
	}
	return ""
}

func (x *Object) GetDateText() string {
	if x != nil {
		return x.xxx_hidden_DateText
	}
	return ""
}

func (x *Object) GetRawHtml() string {
	if x != nil {
		return x.xxx_hidden_RawHtml
	}
	return ""
}

func (x *Object) GetRawText() string {
	if x != nil {
		return x.xxx_hidden_RawText
	}
	return ""
}

func (x *Object) GetDates() *DateSpan {
	if x != nil {
		return x.xxx_hidden_Dates
	}
	return nil
}

func (x *Object) GetTime() *TimeAssoc {
	if x != nil {
		return x.xxx_hidden_Time
	}
	return nil
}

func (x *Object) GetEffects() []*Effect {
	if x != nil {
		if x.xxx_hidden_Effects != nil {
			return *x.xxx_hidden_Effects
		}
	}
	return nil
}

func (x *Object) GetMatchQuality() string {
	if x != nil {
		return x.xxx_hidden_MatchQuality
	}
	return ""
}

func (x *Object) GetPhrase() string {
	if x != nil {
		return x.xxx_hidden_Phrase
	}
	return ""
}

func (x *Object) GetAmenity() string {
	if x != nil {
		return x.xxx_hidden_Amenity
	}
	return ""
}

func (x *Object) GetCandidates() []string {
	if x != nil {
		return x.xxx_hidden_Candidates
	}
	return nil
}

func (x *Object) GetAmbiguities() []string {
	if x != nil {
		return x.xxx_hidden_Ambiguities
	}
	return nil
}

func (x *Object) GetProducedBy() string {
	if x != nil {
		return x.xxx_hidden_ProducedBy
	}
	return ""
}

func (x *Object) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Object) SetKind(v Object_Kind) {
	x.xxx_hidden_Kind = v
}

func (x *Object) SetReason(v string) {
	x.xxx_hidden_Reason = v
}

func (x *Object) SetFacility(v string) {
	x.xxx_hidden_Facility = v
}

func (x *Object) SetSource(v string) {
	x.xxx_hidden_Source = v
}

func (x *Object) SetSourceGroup(v string) {
	x.xxx_hidden_SourceGroup = v
}

func (x *Object) SetSources(v []string) {
	x.xxx_hidden_Sources = v
}

func (x *Object) SetDuplicateOf(v []string) {
	x.xxx_hidden_DuplicateOf = v
}

func (x *Object) SetBlockHash(v string) {
	x.xxx_hidden_BlockHash = v
}

func (x *Object) SetSeq(v int32) {
	x.xxx_hidden_Seq = v
}

func (x *Object) SetHtmlStart(v int32) {
	x.xxx_hidden_HtmlStart = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 25)
}

func (x *Object) SetHtmlEnd(v int32) {
	x.xxx_hidden_HtmlEnd = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 25)
}

func (x *Object) SetSection(v string) {
	x.xxx_hidden_Section = v
}

func (x *Object) SetDateText(v string) {
	x.xxx_hidden_DateText = v
}

func (x *Object) SetRawHtml(v string) {
	x.xxx_hidden_RawHtml = v
}

func (x *Object) SetRawText(v string) {
	x.xxx_hidden_RawText = v
}

func (x *Object) SetDates(v *DateSpan) {
	x.xxx_hidden_Dates = v
}

func (x *Object) SetTime(v *TimeAssoc) {
	x.xxx_hidden_Time = v
}

func (x *Object) SetEffects(v []*Effect) {
	x.xxx_hidden_Effects = &v
}

func (x *Object) SetMatchQuality(v string) {
	x.xxx_hidden_MatchQuality = v
}

func (x *Object) SetPhrase(v string) {
	x.xxx_hidden_Phrase = v
}

func (x *Object) SetAmenity(v string) {
	x.xxx_hidden_Amenity = v
}

func (x *Object) SetCandidates(v []string) {
	x.xxx_hidden_Candidates = v
}

func (x *Object) SetAmbiguities(v []string) {
	x.xxx_hidden_Ambiguities = v
}

func (x *Object) SetProducedBy(v string) {
	x.xxx_hidden_ProducedBy = v
}

func (x *Object) HasHtmlStart() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *Object) HasHtmlEnd() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *Object) HasDates() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Dates != nil
}

func (x *Object) HasTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Time != nil
}

func (x *Object) ClearHtmlStart() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_HtmlStart = 0
}

func (x *Object) ClearHtmlEnd() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_HtmlEnd = 0
}

func (x *Object) ClearDates() {
	x.xxx_hidden_Dates = nil
}

func (x *Object) ClearTime() {
	x.xxx_hidden_Time = nil
}

type Object_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   string
	Kind Object_Kind
	// reason subdivides unparsed (freeform | parse-error) and ignored
	// (heading | date-context | boilerplate | service-desk | duplicate).
	Reason   string
	Facility string
	// source names the HTML field the block came from: special_hours |
	// notifications | schedule_changes.
	Source string
	// source_group is the schedule group whose block this came from (for
	// schedule_changes); the object may be placed elsewhere in the tree when
	// the city posted it under the wrong group (matched-other-group).
	SourceGroup string
	// sources lists all sources that carried this notice when duplicates
	// were collapsed into it (schedule_changes + special_hours).
	Sources []string
	// duplicate_of points from a collapsed ignored/duplicate object to the
	// surviving notice ids.
	DuplicateOf []string
	BlockHash   string
	Seq         int32
	// html_start/html_end are the [start, end) byte range in the source
	// block HTML this fragment was extracted from, when it could be tracked.
	HtmlStart *int32
	HtmlEnd   *int32
	Section   string
	DateText  string
	RawHtml   string
	RawText   string
	Dates     *DateSpan
	Time      *TimeAssoc
	// The notice's effects. Empty for non-notice objects and for notices
	// stating no recognized effect. A consumer on an older schema sees a new
	// effect kind as an Effect element whose oneof is unset: treat those as
	// "unknown effect present", never as no effect.
	Effects []*Effect
	// match_quality: exact | normalized | fuzzy | novel | multiple |
	// scope-phrase | none. candidates holds the raw activity labels of an
	// unresolved multiple match (the object stays at group level).
	MatchQuality string
	Phrase       string
	Amenity      string
	Candidates   []string
	// ambiguities are explicit markers for everything short of certain
	// (see the enrich package docs for the marker vocabulary).
	Ambiguities []string
	ProducedBy  string
}

func (b0 Object_builder) Build() *Object {
	m0 := &Object{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Kind = b.Kind
	x.xxx_hidden_Reason = b.Reason
	x.xxx_hidden_Facility = b.Facility
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_SourceGroup = b.SourceGroup
	x.xxx_hidden_Sources = b.Sources
	x.xxx_hidden_DuplicateOf = b.DuplicateOf
	x.xxx_hidden_BlockHash = b.BlockHash
	x.xxx_hidden_Seq = b.Seq
	if b.HtmlStart != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 25)
		x.xxx_hidden_HtmlStart = *b.HtmlStart
	}
	if b.HtmlEnd != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 25)
		x.xxx_hidden_HtmlEnd = *b.HtmlEnd
	}
	x.xxx_hidden_Section = b.Section
	x.xxx_hidden_DateText = b.DateText
	x.xxx_hidden_RawHtml = b.RawHtml
	x.xxx_hidden_RawText = b.RawText
	x.xxx_hidden_Dates = b.Dates
	x.xxx_hidden_Time = b.Time
	x.xxx_hidden_Effects = &b.Effects
	x.xxx_hidden_MatchQuality = b.MatchQuality
	x.xxx_hidden_Phrase = b.Phrase
	x.xxx_hidden_Amenity = b.Amenity
	x.xxx_hidden_Candidates = b.Candidates
	x.xxx_hidden_Ambiguities = b.Ambiguities
	x.xxx_hidden_ProducedBy = b.ProducedBy
	return m0
}

// DateSpan is a resolved date association.
type DateSpan struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Dates       []int32                `protobuf:"varint,1,rep,packed,name=dates"`
	xxx_hidden_From        int32                  `protobuf:"varint,2,opt,name=from"`
	xxx_hidden_To          int32                  `protobuf:"varint,3,opt,name=to"`
	xxx_hidden_OpenEnded   bool                   `protobuf:"varint,4,opt,name=open_ended,json=openEnded"`
	xxx_hidden_Weekdays    []int32                `protobuf:"varint,5,rep,packed,name=weekdays"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DateSpan) Reset() {
	*x = DateSpan{}
	mi := &file_enrichment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateSpan) ProtoMessage() {}

func (x *DateSpan) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DateSpan) GetDates() []int32 {
	if x != nil {
		return x.xxx_hidden_Dates
	}
	return nil
}

func (x *DateSpan) GetFrom() int32 {
	if x != nil {
		return x.xxx_hidden_From
	}
	return 0
}

func (x *DateSpan) GetTo() int32 {
	if x != nil {
		return x.xxx_hidden_To
	}
	return 0
}

func (x *DateSpan) GetOpenEnded() bool {
	if x != nil {
		return x.xxx_hidden_OpenEnded
	}
	return false
}

func (x *DateSpan) GetWeekdays() []int32 {
	if x != nil {
		return x.xxx_hidden_Weekdays
	}
	return nil
}

func (x *DateSpan) SetDates(v []int32) {
	x.xxx_hidden_Dates = v
}

func (x *DateSpan) SetFrom(v int32) {
	x.xxx_hidden_From = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *DateSpan) SetTo(v int32) {
	x.xxx_hidden_To = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *DateSpan) SetOpenEnded(v bool) {
	x.xxx_hidden_OpenEnded = v
}

func (x *DateSpan) SetWeekdays(v []int32) {
	x.xxx_hidden_Weekdays = v
}

func (x *DateSpan) HasFrom() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DateSpan) HasTo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DateSpan) ClearFrom() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_From = 0
}

func (x *DateSpan) ClearTo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_To = 0
}

type DateSpan_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Dates     []int32
	From      *int32
	To        *int32
	OpenEnded bool
	// weekday-only patterns ("Monday to Friday"), encoded as YYYYMMDDW dates
	// with only the weekday component set.
	Weekdays []int32
}

func (b0 DateSpan_builder) Build() *DateSpan {
	m0 := &DateSpan{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Dates = b.Dates
	if b.From != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_From = *b.From
	}
	if b.To != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_To = *b.To
	}
	x.xxx_hidden_OpenEnded = b.OpenEnded
	x.xxx_hidden_Weekdays = b.Weekdays
	return m0
}

// TimeAssoc is a clock range extracted from a notice and its relation to the
// schedule's actual time slots.
type TimeAssoc struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Text        string                 `protobuf:"bytes,1,opt,name=text"`
	xxx_hidden_Start       int32                  `protobuf:"varint,2,opt,name=start"`
	xxx_hidden_End         int32                  `protobuf:"varint,3,opt,name=end"`
	xxx_hidden_OpenStart   bool                   `protobuf:"varint,4,opt,name=open_start,json=openStart"`
	xxx_hidden_OpenEnd     bool                   `protobuf:"varint,5,opt,name=open_end,json=openEnd"`
	xxx_hidden_Relation    string                 `protobuf:"bytes,6,opt,name=relation"`
	xxx_hidden_Slots       []string               `protobuf:"bytes,7,rep,name=slots"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TimeAssoc) Reset() {
	*x = TimeAssoc{}
	mi := &file_enrichment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeAssoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeAssoc) ProtoMessage() {}

func (x *TimeAssoc) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TimeAssoc) GetText() string {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return ""
}

func (x *TimeAssoc) GetStart() int32 {
	if x != nil {
		return x.xxx_hidden_Start
	}
	return 0
}

func (x *TimeAssoc) GetEnd() int32 {
	if x != nil {
		return x.xxx_hidden_End
	}
	return 0
}

func (x *TimeAssoc) GetOpenStart() bool {
	if x != nil {
		return x.xxx_hidden_OpenStart
	}
	return false
}

func (x *TimeAssoc) GetOpenEnd() bool {
	if x != nil {
		return x.xxx_hidden_OpenEnd
	}
	return false
}

func (x *TimeAssoc) GetRelation() string {
	if x != nil {
		return x.xxx_hidden_Relation
	}
	return ""
}

func (x *TimeAssoc) GetSlots() []string {
	if x != nil {
		return x.xxx_hidden_Slots
	}
	return nil
}

func (x *TimeAssoc) SetText(v string) {
	x.xxx_hidden_Text = v
}

func (x *TimeAssoc) SetStart(v int32) {
	x.xxx_hidden_Start = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *TimeAssoc) SetEnd(v int32) {
	x.xxx_hidden_End = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *TimeAssoc) SetOpenStart(v bool) {
	x.xxx_hidden_OpenStart = v
}

func (x *TimeAssoc) SetOpenEnd(v bool) {
	x.xxx_hidden_OpenEnd = v
}

func (x *TimeAssoc) SetRelation(v string) {
	x.xxx_hidden_Relation = v
}

func (x *TimeAssoc) SetSlots(v []string) {
	x.xxx_hidden_Slots = v
}

func (x *TimeAssoc) HasStart() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TimeAssoc) HasEnd() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TimeAssoc) ClearStart() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Start = 0
}

func (x *TimeAssoc) ClearEnd() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_End = 0
}

type TimeAssoc_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// text/start/end are absent for whole-activity notices where only the
	// affected slots are known.
	Text  string
	Start *int32
	End   *int32
	// open_start/open_end mark single-ended mentions: "closed until noon" is
	// open at the start (affected from start of day), "closed at 7:30 pm" /
	// "will end at 6 pm" open at the end (affected through end of day).
	OpenStart bool
	OpenEnd   bool
	// relation to the matched activity's slots on the resolved dates:
	// exact | within | covers | overlaps | novel | none | unchecked.
	Relation string
	Slots    []string
}

func (b0 TimeAssoc_builder) Build() *TimeAssoc {
	m0 := &TimeAssoc{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Text = b.Text
	if b.Start != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Start = *b.Start
	}
	if b.End != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_End = *b.End
	}
	x.xxx_hidden_OpenStart = b.OpenStart
	x.xxx_hidden_OpenEnd = b.OpenEnd
	x.xxx_hidden_Relation = b.Relation
	x.xxx_hidden_Slots = b.Slots
	return m0
}

// Effect is one best-effort parsed effect of a notice. An effect is only
// ever emitted when its trigger word appears in the raw text, and applies to
// whatever the object's position in the hierarchy scopes it to (a session, a
// whole activity, a group, or the facility) on the object's dates.
//
// Effects are a repeated oneof so the vocabulary can grow: a consumer built
// against an older schema still receives an Effect element for a new kind,
// with the oneof unset (the payload is retained in the unknown fields).
// Callers must therefore treat an Effect with an unset oneof as "an effect
// this consumer doesn't understand" rather than dropping it, e.g. by falling
// back to showing the object's raw text.
type Effect struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Effect isEffect_Effect        `protobuf_oneof:"effect"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Effect) Reset() {
	*x = Effect{}
	mi := &file_enrichment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Effect) GetCancelled() *Effect_Cancelled {
	if x != nil {
		if x, ok := x.xxx_hidden_Effect.(*effect_Cancelled_); ok {
			return x.Cancelled
		}
	}
	return nil
}

func (x *Effect) GetAdded() *Effect_Added {
	if x != nil {
		if x, ok := x.xxx_hidden_Effect.(*effect_Added_); ok {
			return x.Added
		}
	}
	return nil
}

func (x *Effect) GetTimeChange() *Effect_TimeChange {
	if x != nil {
		if x, ok := x.xxx_hidden_Effect.(*effect_TimeChange_); ok {
			return x.TimeChange
		}
	}
	return nil
}

func (x *Effect) GetClosure() *Effect_Closure {
	if x != nil {
		if x, ok := x.xxx_hidden_Effect.(*effect_Closure_); ok {
			return x.Closure
		}
	}
	return nil
}

func (x *Effect) GetSeasonalHours() *Effect_SeasonalHours {
	if x != nil {
		if x, ok := x.xxx_hidden_Effect.(*effect_SeasonalHours_); ok {
			return x.SeasonalHours
		}
	}
	return nil
}

func (x *Effect) GetModifiedHours() *Effect_ModifiedHours {
	if x != nil {
		if x, ok := x.xxx_hidden_Effect.(*effect_ModifiedHours_); ok {
			return x.ModifiedHours
		}
	}
	return nil
}

func (x *Effect) GetMovedTo() *Effect_MovedTo {
	if x != nil {
		if x, ok := x.xxx_hidden_Effect.(*effect_MovedTo_); ok {
			return x.MovedTo
		}
	}
	return nil
}

func (x *Effect) GetChangedTo() *Effect_ChangedTo {
	if x != nil {
		if x, ok := x.xxx_hidden_Effect.(*effect_ChangedTo_); ok {
			return x.ChangedTo
		}
	}
	return nil
}

func (x *Effect) GetRestriction() *Effect_Restriction {
	if x != nil {
		if x, ok := x.xxx_hidden_Effect.(*effect_Restriction_); ok {
			return x.Restriction
		}
	}
	return nil
}

func (x *Effect) GetSeeSchedule() *Effect_SeeSchedule {
	if x != nil {
		if x, ok := x.xxx_hidden_Effect.(*effect_SeeSchedule_); ok {
			return x.SeeSchedule
		}
	}
	return nil
}

func (x *Effect) SetCancelled(v *Effect_Cancelled) {
	if v == nil {
		x.xxx_hidden_Effect = nil
		return
	}
	x.xxx_hidden_Effect = &effect_Cancelled_{v}
}

func (x *Effect) SetAdded(v *Effect_Added) {
	if v == nil {
		x.xxx_hidden_Effect = nil
		return
	}
	x.xxx_hidden_Effect = &effect_Added_{v}
}

func (x *Effect) SetTimeChange(v *Effect_TimeChange) {
	if v == nil {
		x.xxx_hidden_Effect = nil
		return
	}
	x.xxx_hidden_Effect = &effect_TimeChange_{v}
}

func (x *Effect) SetClosure(v *Effect_Closure) {
	if v == nil {
		x.xxx_hidden_Effect = nil
		return
	}
	x.xxx_hidden_Effect = &effect_Closure_{v}
}

func (x *Effect) SetSeasonalHours(v *Effect_SeasonalHours) {
	if v == nil {
		x.xxx_hidden_Effect = nil
		return
	}
	x.xxx_hidden_Effect = &effect_SeasonalHours_{v}
}

func (x *Effect) SetModifiedHours(v *Effect_ModifiedHours) {
	if v == nil {
		x.xxx_hidden_Effect = nil
		return
	}
	x.xxx_hidden_Effect = &effect_ModifiedHours_{v}
}

func (x *Effect) SetMovedTo(v *Effect_MovedTo) {
	if v == nil {
		x.xxx_hidden_Effect = nil
		return
	}
	x.xxx_hidden_Effect = &effect_MovedTo_{v}
}

func (x *Effect) SetChangedTo(v *Effect_ChangedTo) {
	if v == nil {
		x.xxx_hidden_Effect = nil
		return
	}
	x.xxx_hidden_Effect = &effect_ChangedTo_{v}
}

func (x *Effect) SetRestriction(v *Effect_Restriction) {
	if v == nil {
		x.xxx_hidden_Effect = nil
		return
	}
	x.xxx_hidden_Effect = &effect_Restriction_{v}
}

func (x *Effect) SetSeeSchedule(v *Effect_SeeSchedule) {
	if v == nil {
		x.xxx_hidden_Effect = nil
		return
	}
	x.xxx_hidden_Effect = &effect_SeeSchedule_{v}
}

func (x *Effect) HasEffect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Effect != nil
}

func (x *Effect) HasCancelled() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Effect.(*effect_Cancelled_)
	return ok
}

func (x *Effect) HasAdded() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Effect.(*effect_Added_)
	return ok
}

func (x *Effect) HasTimeChange() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Effect.(*effect_TimeChange_)
	return ok
}

func (x *Effect) HasClosure() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Effect.(*effect_Closure_)
	return ok
}

func (x *Effect) HasSeasonalHours() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Effect.(*effect_SeasonalHours_)
	return ok
}

func (x *Effect) HasModifiedHours() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Effect.(*effect_ModifiedHours_)
	return ok
}

func (x *Effect) HasMovedTo() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Effect.(*effect_MovedTo_)
	return ok
}

func (x *Effect) HasChangedTo() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Effect.(*effect_ChangedTo_)
	return ok
}

func (x *Effect) HasRestriction() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Effect.(*effect_Restriction_)
	return ok
}

func (x *Effect) HasSeeSchedule() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Effect.(*effect_SeeSchedule_)
	return ok
}

func (x *Effect) ClearEffect() {
	x.xxx_hidden_Effect = nil
}

func (x *Effect) ClearCancelled() {
	if _, ok := x.xxx_hidden_Effect.(*effect_Cancelled_); ok {
		x.xxx_hidden_Effect = nil
	}
}

func (x *Effect) ClearAdded() {
	if _, ok := x.xxx_hidden_Effect.(*effect_Added_); ok {
		x.xxx_hidden_Effect = nil
	}
}

func (x *Effect) ClearTimeChange() {
	if _, ok := x.xxx_hidden_Effect.(*effect_TimeChange_); ok {
		x.xxx_hidden_Effect = nil
	}
}

func (x *Effect) ClearClosure() {
	if _, ok := x.xxx_hidden_Effect.(*effect_Closure_); ok {
		x.xxx_hidden_Effect = nil
	}
}

func (x *Effect) ClearSeasonalHours() {
	if _, ok := x.xxx_hidden_Effect.(*effect_SeasonalHours_); ok {
		x.xxx_hidden_Effect = nil
	}
}

func (x *Effect) ClearModifiedHours() {
	if _, ok := x.xxx_hidden_Effect.(*effect_ModifiedHours_); ok {
		x.xxx_hidden_Effect = nil
	}
}

func (x *Effect) ClearMovedTo() {
	if _, ok := x.xxx_hidden_Effect.(*effect_MovedTo_); ok {
		x.xxx_hidden_Effect = nil
	}
}

func (x *Effect) ClearChangedTo() {
	if _, ok := x.xxx_hidden_Effect.(*effect_ChangedTo_); ok {
		x.xxx_hidden_Effect = nil
	}
}

func (x *Effect) ClearRestriction() {
	if _, ok := x.xxx_hidden_Effect.(*effect_Restriction_); ok {
		x.xxx_hidden_Effect = nil
	}
}

func (x *Effect) ClearSeeSchedule() {
	if _, ok := x.xxx_hidden_Effect.(*effect_SeeSchedule_); ok {
		x.xxx_hidden_Effect = nil
	}
}

const Effect_Effect_not_set_case case_Effect_Effect = 0
const Effect_Cancelled_case case_Effect_Effect = 1
const Effect_Added_case case_Effect_Effect = 2
const Effect_TimeChange_case case_Effect_Effect = 3
const Effect_Closure_case case_Effect_Effect = 4
const Effect_SeasonalHours_case case_Effect_Effect = 5
const Effect_ModifiedHours_case case_Effect_Effect = 6
const Effect_MovedTo_case case_Effect_Effect = 7
const Effect_ChangedTo_case case_Effect_Effect = 8
const Effect_Restriction_case case_Effect_Effect = 9
const Effect_SeeSchedule_case case_Effect_Effect = 10

func (x *Effect) WhichEffect() case_Effect_Effect {
	if x == nil {
		return Effect_Effect_not_set_case
	}
	switch x.xxx_hidden_Effect.(type) {
	case *effect_Cancelled_:
		return Effect_Cancelled_case
	case *effect_Added_:
		return Effect_Added_case
	case *effect_TimeChange_:
		return Effect_TimeChange_case
	case *effect_Closure_:
		return Effect_Closure_case
	case *effect_SeasonalHours_:
		return Effect_SeasonalHours_case
	case *effect_ModifiedHours_:
		return Effect_ModifiedHours_case
	case *effect_MovedTo_:
		return Effect_MovedTo_case
	case *effect_ChangedTo_:
		return Effect_ChangedTo_case
	case *effect_Restriction_:
		return Effect_Restriction_case
	case *effect_SeeSchedule_:
		return Effect_SeeSchedule_case
	default:
		return Effect_Effect_not_set_case
	}
}

type Effect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Effect:
	Cancelled     *Effect_Cancelled
	Added         *Effect_Added
	TimeChange    *Effect_TimeChange
	Closure       *Effect_Closure
	SeasonalHours *Effect_SeasonalHours
	ModifiedHours *Effect_ModifiedHours
	MovedTo       *Effect_MovedTo
	ChangedTo     *Effect_ChangedTo
	Restriction   *Effect_Restriction
	SeeSchedule   *Effect_SeeSchedule
	// -- end of xxx_hidden_Effect
}

func (b0 Effect_builder) Build() *Effect {
	m0 := &Effect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cancelled != nil {
		x.xxx_hidden_Effect = &effect_Cancelled_{b.Cancelled}
	}
	if b.Added != nil {
		x.xxx_hidden_Effect = &effect_Added_{b.Added}
	}
	if b.TimeChange != nil {
		x.xxx_hidden_Effect = &effect_TimeChange_{b.TimeChange}
	}
	if b.Closure != nil {
		x.xxx_hidden_Effect = &effect_Closure_{b.Closure}
	}
	if b.SeasonalHours != nil {
		x.xxx_hidden_Effect = &effect_SeasonalHours_{b.SeasonalHours}
	}
	if b.ModifiedHours != nil {
		x.xxx_hidden_Effect = &effect_ModifiedHours_{b.ModifiedHours}
	}
	if b.MovedTo != nil {
		x.xxx_hidden_Effect = &effect_MovedTo_{b.MovedTo}
	}
	if b.ChangedTo != nil {
		x.xxx_hidden_Effect = &effect_ChangedTo_{b.ChangedTo}
	}
	if b.Restriction != nil {
		x.xxx_hidden_Effect = &effect_Restriction_{b.Restriction}
	}
	if b.SeeSchedule != nil {
		x.xxx_hidden_Effect = &effect_SeeSchedule_{b.SeeSchedule}
	}
	return m0
}

type case_Effect_Effect protoreflect.FieldNumber

func (x case_Effect_Effect) String() string {
	md := file_enrichment_proto_msgTypes[8].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isEffect_Effect interface {
	isEffect_Effect()
}

type effect_Cancelled_ struct {
	Cancelled *Effect_Cancelled `protobuf:"bytes,1,opt,name=cancelled,oneof"`
}

type effect_Added_ struct {
	Added *Effect_Added `protobuf:"bytes,2,opt,name=added,oneof"`
}

type effect_TimeChange_ struct {
	TimeChange *Effect_TimeChange `protobuf:"bytes,3,opt,name=time_change,json=timeChange,oneof"`
}

type effect_Closure_ struct {
	Closure *Effect_Closure `protobuf:"bytes,4,opt,name=closure,oneof"`
}

type effect_SeasonalHours_ struct {
	SeasonalHours *Effect_SeasonalHours `protobuf:"bytes,5,opt,name=seasonal_hours,json=seasonalHours,oneof"`
}

type effect_ModifiedHours_ struct {
	ModifiedHours *Effect_ModifiedHours `protobuf:"bytes,6,opt,name=modified_hours,json=modifiedHours,oneof"`
}

type effect_MovedTo_ struct {
	MovedTo *Effect_MovedTo `protobuf:"bytes,7,opt,name=moved_to,json=movedTo,oneof"`
}

type effect_ChangedTo_ struct {
	ChangedTo *Effect_ChangedTo `protobuf:"bytes,8,opt,name=changed_to,json=changedTo,oneof"`
}

type effect_Restriction_ struct {
	Restriction *Effect_Restriction `protobuf:"bytes,9,opt,name=restriction,oneof"`
}

type effect_SeeSchedule_ struct {
	SeeSchedule *Effect_SeeSchedule `protobuf:"bytes,10,opt,name=see_schedule,json=seeSchedule,oneof"`
}

func (*effect_Cancelled_) isEffect_Effect() {}

func (*effect_Added_) isEffect_Effect() {}

func (*effect_TimeChange_) isEffect_Effect() {}

func (*effect_Closure_) isEffect_Effect() {}

func (*effect_SeasonalHours_) isEffect_Effect() {}

func (*effect_ModifiedHours_) isEffect_Effect() {}

func (*effect_MovedTo_) isEffect_Effect() {}

func (*effect_ChangedTo_) isEffect_Effect() {}

func (*effect_Restriction_) isEffect_Effect() {}

func (*effect_SeeSchedule_) isEffect_Effect() {}

// The session/activity/scope is cancelled on the object's dates.
type Effect_Cancelled struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect_Cancelled) Reset() {
	*x = Effect_Cancelled{}
	mi := &file_enrichment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_Cancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_Cancelled) ProtoMessage() {}

func (x *Effect_Cancelled) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Effect_Cancelled_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Effect_Cancelled_builder) Build() *Effect_Cancelled {
	m0 := &Effect_Cancelled{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// The session (see Session.added) or activity is added on the object's
// dates; the time is not part of the published schedule.
type Effect_Added struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect_Added) Reset() {
	*x = Effect_Added{}
	mi := &file_enrichment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_Added) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_Added) ProtoMessage() {}

func (x *Effect_Added) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Effect_Added_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Effect_Added_builder) Build() *Effect_Added {
	m0 := &Effect_Added{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// The time changed ("schedule change", "will end at 6 pm", or a
// changed-to with new times); details are in the object's time and
// raw text.
type Effect_TimeChange struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect_TimeChange) Reset() {
	*x = Effect_TimeChange{}
	mi := &file_enrichment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_TimeChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_TimeChange) ProtoMessage() {}

func (x *Effect_TimeChange) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Effect_TimeChange_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Effect_TimeChange_builder) Build() *Effect_TimeChange {
	m0 := &Effect_TimeChange{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// The scope (facility, amenity, or activity subject) is closed. With
// dates and/or a time this is bounded; combined with
// DateSpan.open_ended it is "until further notice".
type Effect_Closure struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect_Closure) Reset() {
	*x = Effect_Closure{}
	mi := &file_enrichment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_Closure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_Closure) ProtoMessage() {}

func (x *Effect_Closure) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Effect_Closure_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Effect_Closure_builder) Build() *Effect_Closure {
	m0 := &Effect_Closure{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// The object's dates are a seasonal operating range ("Regular season,
// June 29 to August 30", "Closed for the season").
type Effect_SeasonalHours struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect_SeasonalHours) Reset() {
	*x = Effect_SeasonalHours{}
	mi := &file_enrichment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_SeasonalHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_SeasonalHours) ProtoMessage() {}

func (x *Effect_SeasonalHours) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Effect_SeasonalHours_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Effect_SeasonalHours_builder) Build() *Effect_SeasonalHours {
	m0 := &Effect_SeasonalHours{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// The object's dates+time are the facility's operating hours for those
// dates (holiday/modified hours), not an activity time.
type Effect_ModifiedHours struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect_ModifiedHours) Reset() {
	*x = Effect_ModifiedHours{}
	mi := &file_enrichment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_ModifiedHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_ModifiedHours) ProtoMessage() {}

func (x *Effect_ModifiedHours) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Effect_ModifiedHours_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Effect_ModifiedHours_builder) Build() *Effect_ModifiedHours {
	m0 := &Effect_ModifiedHours{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// The activity moved elsewhere ("moved to the 25m pool"); to is the raw
// destination text.
type Effect_MovedTo struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_To string                 `protobuf:"bytes,1,opt,name=to"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect_MovedTo) Reset() {
	*x = Effect_MovedTo{}
	mi := &file_enrichment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_MovedTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_MovedTo) ProtoMessage() {}

func (x *Effect_MovedTo) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Effect_MovedTo) GetTo() string {
	if x != nil {
		return x.xxx_hidden_To
	}
	return ""
}

func (x *Effect_MovedTo) SetTo(v string) {
	x.xxx_hidden_To = v
}

type Effect_MovedTo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	To string
}

func (b0 Effect_MovedTo_builder) Build() *Effect_MovedTo {
	m0 := &Effect_MovedTo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_To = b.To
	return m0
}

// The activity changed to something else ("changed to Lane swim -
// shared pool"); to is the raw replacement text (may name an activity
// or new times).
type Effect_ChangedTo struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_To string                 `protobuf:"bytes,1,opt,name=to"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect_ChangedTo) Reset() {
	*x = Effect_ChangedTo{}
	mi := &file_enrichment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_ChangedTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_ChangedTo) ProtoMessage() {}

func (x *Effect_ChangedTo) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Effect_ChangedTo) GetTo() string {
	if x != nil {
		return x.xxx_hidden_To
	}
	return ""
}

func (x *Effect_ChangedTo) SetTo(v string) {
	x.xxx_hidden_To = v
}

type Effect_ChangedTo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	To string
}

func (b0 Effect_ChangedTo_builder) Build() *Effect_ChangedTo {
	m0 := &Effect_ChangedTo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_To = b.To
	return m0
}

// A restriction applies ("25m pool only", "short course only"); text is
// the raw restriction clause.
type Effect_Restriction struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Text string                 `protobuf:"bytes,1,opt,name=text"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Effect_Restriction) Reset() {
	*x = Effect_Restriction{}
	mi := &file_enrichment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_Restriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_Restriction) ProtoMessage() {}

func (x *Effect_Restriction) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Effect_Restriction) GetText() string {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return ""
}

func (x *Effect_Restriction) SetText(v string) {
	x.xxx_hidden_Text = v
}

type Effect_Restriction_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Text string
}

func (b0 Effect_Restriction_builder) Build() *Effect_Restriction {
	m0 := &Effect_Restriction{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Text = b.Text
	return m0
}

// The notice defers to another schedule ("See Winter Break schedule").
type Effect_SeeSchedule struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Url  string                 `protobuf:"bytes,2,opt,name=url"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Effect_SeeSchedule) Reset() {
	*x = Effect_SeeSchedule{}
	mi := &file_enrichment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect_SeeSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_SeeSchedule) ProtoMessage() {}

func (x *Effect_SeeSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Effect_SeeSchedule) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Effect_SeeSchedule) GetUrl() string {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return ""
}

func (x *Effect_SeeSchedule) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Effect_SeeSchedule) SetUrl(v string) {
	x.xxx_hidden_Url = v
}

type Effect_SeeSchedule_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name string
	Url  string
}

func (b0 Effect_SeeSchedule_builder) Build() *Effect_SeeSchedule {
	m0 := &Effect_SeeSchedule{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Url = b.Url
	return m0
}

var File_enrichment_proto protoreflect.FileDescriptor

const file_enrichment_proto_rawDesc = "" +
	"\n" +
	"\x10enrichment.proto\x12\x14ottrec.enrichment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x02\n" +
	"\x06Output\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x128\n" +
	"\tgenerated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tgenerated\x126\n" +
	"\aobjects\x18\x03 \x03(\v2\x1c.ottrec.enrichment.v1.ObjectR\aobjects\x12>\n" +
	"\n" +
	"facilities\x18\x04 \x03(\v2\x1e.ottrec.enrichment.v1.FacilityR\n" +
	"facilities\x12=\n" +
	"\x05stats\x18\x05 \x03(\v2'.ottrec.enrichment.v1.Output.StatsEntryR\x05stats\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"m\n" +
	"\bFacility\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aobjects\x18\x02 \x03(\tR\aobjects\x123\n" +
	"\x06groups\x18\x03 \x03(\v2\x1b.ottrec.enrichment.v1.GroupR\x06groups\"w\n" +
	"\x05Group\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x18\n" +
	"\aobjects\x18\x02 \x03(\tR\aobjects\x12>\n" +
	"\n" +
	"activities\x18\x03 \x03(\v2\x1e.ottrec.enrichment.v1.ActivityR\n" +
	"activities\"\x8b\x01\n" +
	"\bActivity\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05novel\x18\x02 \x01(\bR\x05novel\x12\x18\n" +
	"\aobjects\x18\x03 \x03(\tR\aobjects\x129\n" +
	"\bsessions\x18\x04 \x03(\v2\x1d.ottrec.enrichment.v1.SessionR\bsessions\"u\n" +
	"\aSession\x12\x12\n" +
	"\x04date\x18\x01 \x01(\x05R\x04date\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x05R\x03end\x12\x18\n" +
	"\aobjects\x18\x04 \x03(\tR\aobjects\x12\x14\n" +
	"\x05added\x18\x05 \x03(\tR\x05added\"\x91\a\n" +
	"\x06Object\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x04kind\x18\x02 \x01(\x0e2!.ottrec.enrichment.v1.Object.KindR\x04kind\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1a\n" +
	"\bfacility\x18\x04 \x01(\tR\bfacility\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12!\n" +
	"\fsource_group\x18\x06 \x01(\tR\vsourceGroup\x12\x18\n" +
	"\asources\x18\a \x03(\tR\asources\x12!\n" +
	"\fduplicate_of\x18\b \x03(\tR\vduplicateOf\x12\x1d\n" +
	"\n" +
	"block_hash\x18\t \x01(\tR\tblockHash\x12\x10\n" +
	"\x03seq\x18\n" +
	" \x01(\x05R\x03seq\x12$\n" +
	"\n" +
	"html_start\x18\v \x01(\x05B\x05\xaa\x01\x02\b\x01R\thtmlStart\x12 \n" +
	"\bhtml_end\x18\f \x01(\x05B\x05\xaa\x01\x02\b\x01R\ahtmlEnd\x12\x18\n" +
	"\asection\x18\r \x01(\tR\asection\x12\x1b\n" +
	"\tdate_text\x18\x0e \x01(\tR\bdateText\x12\x19\n" +
	"\braw_html\x18\x0f \x01(\tR\arawHtml\x12\x19\n" +
	"\braw_text\x18\x10 \x01(\tR\arawText\x12;\n" +
	"\x05dates\x18\x11 \x01(\v2\x1e.ottrec.enrichment.v1.DateSpanB\x05\xaa\x01\x02\b\x01R\x05dates\x12:\n" +
	"\x04time\x18\x12 \x01(\v2\x1f.ottrec.enrichment.v1.TimeAssocB\x05\xaa\x01\x02\b\x01R\x04time\x126\n" +
	"\aeffects\x18\x13 \x03(\v2\x1c.ottrec.enrichment.v1.EffectR\aeffects\x12#\n" +
	"\rmatch_quality\x18\x14 \x01(\tR\fmatchQuality\x12\x16\n" +
	"\x06phrase\x18\x15 \x01(\tR\x06phrase\x12\x18\n" +
	"\aamenity\x18\x16 \x01(\tR\aamenity\x12\x1e\n" +
	"\n" +
	"candidates\x18\x17 \x03(\tR\n" +
	"candidates\x12 \n" +
	"\vambiguities\x18\x18 \x03(\tR\vambiguities\x12\x1f\n" +
	"\vproduced_by\x18\x19 \x01(\tR\n" +
	"producedBy\"C\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06NOTICE\x10\x01\x12\f\n" +
	"\bUNPARSED\x10\x02\x12\v\n" +
	"\aIGNORED\x10\x03\"\x8d\x01\n" +
	"\bDateSpan\x12\x14\n" +
	"\x05dates\x18\x01 \x03(\x05R\x05dates\x12\x19\n" +
	"\x04from\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x04from\x12\x15\n" +
	"\x02to\x18\x03 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x02to\x12\x1d\n" +
	"\n" +
	"open_ended\x18\x04 \x01(\bR\topenEnded\x12\x1a\n" +
	"\bweekdays\x18\x05 \x03(\x05R\bweekdays\"\xc1\x01\n" +
	"\tTimeAssoc\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n" +
	"\x05start\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x05start\x12\x17\n" +
	"\x03end\x18\x03 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x03end\x12\x1d\n" +
	"\n" +
	"open_start\x18\x04 \x01(\bR\topenStart\x12\x19\n" +
	"\bopen_end\x18\x05 \x01(\bR\aopenEnd\x12\x1a\n" +
	"\brelation\x18\x06 \x01(\tR\brelation\x12\x14\n" +
	"\x05slots\x18\a \x03(\tR\x05slots\"\xd8\a\n" +
	"\x06Effect\x12F\n" +
	"\tcancelled\x18\x01 \x01(\v2&.ottrec.enrichment.v1.Effect.CancelledH\x00R\tcancelled\x12:\n" +
	"\x05added\x18\x02 \x01(\v2\".ottrec.enrichment.v1.Effect.AddedH\x00R\x05added\x12J\n" +
	"\vtime_change\x18\x03 \x01(\v2'.ottrec.enrichment.v1.Effect.TimeChangeH\x00R\n" +
	"timeChange\x12@\n" +
	"\aclosure\x18\x04 \x01(\v2$.ottrec.enrichment.v1.Effect.ClosureH\x00R\aclosure\x12S\n" +
	"\x0eseasonal_hours\x18\x05 \x01(\v2*.ottrec.enrichment.v1.Effect.SeasonalHoursH\x00R\rseasonalHours\x12S\n" +
	"\x0emodified_hours\x18\x06 \x01(\v2*.ottrec.enrichment.v1.Effect.ModifiedHoursH\x00R\rmodifiedHours\x12A\n" +
	"\bmoved_to\x18\a \x01(\v2$.ottrec.enrichment.v1.Effect.MovedToH\x00R\amovedTo\x12G\n" +
	"\n" +
	"changed_to\x18\b \x01(\v2&.ottrec.enrichment.v1.Effect.ChangedToH\x00R\tchangedTo\x12L\n" +
	"\vrestriction\x18\t \x01(\v2(.ottrec.enrichment.v1.Effect.RestrictionH\x00R\vrestriction\x12M\n" +
	"\fsee_schedule\x18\n" +
	" \x01(\v2(.ottrec.enrichment.v1.Effect.SeeScheduleH\x00R\vseeSchedule\x1a\v\n" +
	"\tCancelled\x1a\a\n" +
	"\x05Added\x1a\f\n" +
	"\n" +
	"TimeChange\x1a\t\n" +
	"\aClosure\x1a\x0f\n" +
	"\rSeasonalHours\x1a\x0f\n" +
	"\rModifiedHours\x1a\x19\n" +
	"\aMovedTo\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x1a\x1b\n" +
	"\tChangedTo\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x1a!\n" +
	"\vRestriction\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x1a3\n" +
	"\vSeeSchedule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03urlB\b\n" +
	"\x06effectB\x05\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_enrichment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enrichment_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_enrichment_proto_goTypes = []any{
	(Object_Kind)(0),              // 0: ottrec.enrichment.v1.Object.Kind
	(*Output)(nil),                // 1: ottrec.enrichment.v1.Output
	(*Facility)(nil),              // 2: ottrec.enrichment.v1.Facility
	(*Group)(nil),                 // 3: ottrec.enrichment.v1.Group
	(*Activity)(nil),              // 4: ottrec.enrichment.v1.Activity
	(*Session)(nil),               // 5: ottrec.enrichment.v1.Session
	(*Object)(nil),                // 6: ottrec.enrichment.v1.Object
	(*DateSpan)(nil),              // 7: ottrec.enrichment.v1.DateSpan
	(*TimeAssoc)(nil),             // 8: ottrec.enrichment.v1.TimeAssoc
	(*Effect)(nil),                // 9: ottrec.enrichment.v1.Effect
	nil,                           // 10: ottrec.enrichment.v1.Output.StatsEntry
	(*Effect_Cancelled)(nil),      // 11: ottrec.enrichment.v1.Effect.Cancelled
	(*Effect_Added)(nil),          // 12: ottrec.enrichment.v1.Effect.Added
	(*Effect_TimeChange)(nil),     // 13: ottrec.enrichment.v1.Effect.TimeChange
	(*Effect_Closure)(nil),        // 14: ottrec.enrichment.v1.Effect.Closure
	(*Effect_SeasonalHours)(nil),  // 15: ottrec.enrichment.v1.Effect.SeasonalHours
	(*Effect_ModifiedHours)(nil),  // 16: ottrec.enrichment.v1.Effect.ModifiedHours
	(*Effect_MovedTo)(nil),        // 17: ottrec.enrichment.v1.Effect.MovedTo
	(*Effect_ChangedTo)(nil),      // 18: ottrec.enrichment.v1.Effect.ChangedTo
	(*Effect_Restriction)(nil),    // 19: ottrec.enrichment.v1.Effect.Restriction
	(*Effect_SeeSchedule)(nil),    // 20: ottrec.enrichment.v1.Effect.SeeSchedule
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_enrichment_proto_depIdxs = []int32{
	21, // 0: ottrec.enrichment.v1.Output.generated:type_name -> google.protobuf.Timestamp
	6,  // 1: ottrec.enrichment.v1.Output.objects:type_name -> ottrec.enrichment.v1.Object
	2,  // 2: ottrec.enrichment.v1.Output.facilities:type_name -> ottrec.enrichment.v1.Facility
	10, // 3: ottrec.enrichment.v1.Output.stats:type_name -> ottrec.enrichment.v1.Output.StatsEntry
	3,  // 4: ottrec.enrichment.v1.Facility.groups:type_name -> ottrec.enrichment.v1.Group
	4,  // 5: ottrec.enrichment.v1.Group.activities:type_name -> ottrec.enrichment.v1.Activity
	5,  // 6: ottrec.enrichment.v1.Activity.sessions:type_name -> ottrec.enrichment.v1.Session
	0,  // 7: ottrec.enrichment.v1.Object.kind:type_name -> ottrec.enrichment.v1.Object.Kind
	7,  // 8: ottrec.enrichment.v1.Object.dates:type_name -> ottrec.enrichment.v1.DateSpan
	8,  // 9: ottrec.enrichment.v1.Object.time:type_name -> ottrec.enrichment.v1.TimeAssoc
	9,  // 10: ottrec.enrichment.v1.Object.effects:type_name -> ottrec.enrichment.v1.Effect
	11, // 11: ottrec.enrichment.v1.Effect.cancelled:type_name -> ottrec.enrichment.v1.Effect.Cancelled
	12, // 12: ottrec.enrichment.v1.Effect.added:type_name -> ottrec.enrichment.v1.Effect.Added
	13, // 13: ottrec.enrichment.v1.Effect.time_change:type_name -> ottrec.enrichment.v1.Effect.TimeChange
	14, // 14: ottrec.enrichment.v1.Effect.closure:type_name -> ottrec.enrichment.v1.Effect.Closure
	15, // 15: ottrec.enrichment.v1.Effect.seasonal_hours:type_name -> ottrec.enrichment.v1.Effect.SeasonalHours
	16, // 16: ottrec.enrichment.v1.Effect.modified_hours:type_name -> ottrec.enrichment.v1.Effect.ModifiedHours
	17, // 17: ottrec.enrichment.v1.Effect.moved_to:type_name -> ottrec.enrichment.v1.Effect.MovedTo
	18, // 18: ottrec.enrichment.v1.Effect.changed_to:type_name -> ottrec.enrichment.v1.Effect.ChangedTo
	19, // 19: ottrec.enrichment.v1.Effect.restriction:type_name -> ottrec.enrichment.v1.Effect.Restriction
	20, // 20: ottrec.enrichment.v1.Effect.see_schedule:type_name -> ottrec.enrichment.v1.Effect.SeeSchedule
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_enrichment_proto_init() }
func file_enrichment_proto_init() {
	if File_enrichment_proto != nil {
		return
	}
	file_enrichment_proto_msgTypes[8].OneofWrappers = []any{
		(*effect_Cancelled_)(nil),
		(*effect_Added_)(nil),
		(*effect_TimeChange_)(nil),
		(*effect_Closure_)(nil),
		(*effect_SeasonalHours_)(nil),
		(*effect_ModifiedHours_)(nil),
		(*effect_MovedTo_)(nil),
		(*effect_ChangedTo_)(nil),
		(*effect_Restriction_)(nil),
		(*effect_SeeSchedule_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enrichment_proto_rawDesc), len(file_enrichment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enrichment_proto_goTypes,
		DependencyIndexes: file_enrichment_proto_depIdxs,
		EnumInfos:         file_enrichment_proto_enumTypes,
		MessageInfos:      file_enrichment_proto_msgTypes,
	}.Build()
	File_enrichment_proto = out.File
	file_enrichment_proto_goTypes = nil
	file_enrichment_proto_depIdxs = nil
}
